fix: commented out clear space

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -46,20 +46,20 @@ jobs:
             esac
           fi
 
-      - name: Free up disk space on runner
-        run: |
-          echo "Initial disk usage:"
-          df -h
-          sudo rm -rf /usr/share/dotnet \
-                      /opt/ghc \
-                      /usr/local/share/boost \
-                      /usr/local/lib/android \
-                      /opt/hostedtoolcache \
-                      /usr/share/swift \
-                      /usr/local/share/powershell
-          docker system prune -af --volumes || true
-          echo "After cleanup:"
-          df -h
+      # - name: Free up disk space on runner
+      #   run: |
+      #     echo "Initial disk usage:"
+      #     df -h
+      #     sudo rm -rf /usr/share/dotnet \
+      #                 /opt/ghc \
+      #                 /usr/local/share/boost \
+      #                 /usr/local/lib/android \
+      #                 /opt/hostedtoolcache \
+      #                 /usr/share/swift \
+      #                 /usr/local/share/powershell
+      #     docker system prune -af --volumes || true
+      #     echo "After cleanup:"
+      #     df -h
 
       - name: Fetch Latest ERPNext Release Tag and Date
         id: get_erpnext_tag
