feat: removed freeing up space

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -115,20 +115,20 @@ jobs:
           echo "FRAPPE_BRANCH_FOR_BUILD: $FRAPPE_BRANCH_FOR_BUILD"
           echo "IMAGE_TAG_VERSION: $IMAGE_TAG_VERSION"
 
-      - name: Free up disk space on runner (again, after fetching release)
-        if: runner.os != 'Windows'
-        run: |
-          echo "Initial disk space:"
-          df -h
-          echo "Attempting to remove large pre-installed toolsets..."
-          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android /opt/hostedtoolcache/CodeQL || true
-          echo "Attempting to prune Docker system..."
-          sudo docker system prune -af --volumes || true
-          echo "Attempting to clean apt cache..."
-          sudo apt-get clean || true
-          sudo rm -rf /var/lib/apt/lists/* || true
-          echo "Disk space after cleanup attempts:"
-          df -h
+      # - name: Free up disk space on runner (again, after fetching release)
+      #   if: runner.os != 'Windows'
+      #   run: |
+      #     echo "Initial disk space:"
+      #     df -h
+      #     echo "Attempting to remove large pre-installed toolsets..."
+      #     sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android /opt/hostedtoolcache/CodeQL || true
+      #     echo "Attempting to prune Docker system..."
+      #     sudo docker system prune -af --volumes || true
+      #     echo "Attempting to clean apt cache..."
+      #     sudo apt-get clean || true
+      #     sudo rm -rf /var/lib/apt/lists/* || true
+      #     echo "Disk space after cleanup attempts:"
+      #     df -h
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
